package com.dnsspeedtest.app.dns

object DnsServerCatalog {
    val all: List<DnsServer> = listOf(
        DnsServer(
            id = "cf-doh",
            name = "Cloudflare",
            protocol = DnsProtocol.DOH,
            host = "cloudflare-dns.com",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("1.1.1.1", "1.0.0.1"),
            sni = "cloudflare-dns.com",
        ),
        DnsServer(
            id = "cf-dot",
            name = "Cloudflare",
            protocol = DnsProtocol.DOT,
            host = "1.1.1.1",
            port = 853,
            bootstrapIps = listOf("1.1.1.1", "1.0.0.1"),
            sni = "cloudflare-dns.com",
        ),
        DnsServer(
            id = "google-doh",
            name = "Google",
            protocol = DnsProtocol.DOH,
            host = "dns.google",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("8.8.8.8", "8.8.4.4"),
            sni = "dns.google",
        ),
        DnsServer(
            id = "google-dot",
            name = "Google",
            protocol = DnsProtocol.DOT,
            host = "8.8.8.8",
            port = 853,
            bootstrapIps = listOf("8.8.8.8", "8.8.4.4"),
            sni = "dns.google",
        ),
        DnsServer(
            id = "quad9-doh",
            name = "Quad9",
            protocol = DnsProtocol.DOH,
            host = "dns.quad9.net",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("9.9.9.9", "149.112.112.112"),
            sni = "dns.quad9.net",
        ),
        DnsServer(
            id = "quad9-dot",
            name = "Quad9",
            protocol = DnsProtocol.DOT,
            host = "9.9.9.9",
            port = 853,
            bootstrapIps = listOf("9.9.9.9", "149.112.112.112"),
            sni = "dns.quad9.net",
        ),
        DnsServer(
            id = "adguard-doh",
            name = "AdGuard",
            protocol = DnsProtocol.DOH,
            host = "dns.adguard-dns.com",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("94.140.14.14", "94.140.15.15"),
            sni = "dns.adguard-dns.com",
        ),
        DnsServer(
            id = "adguard-dot",
            name = "AdGuard",
            protocol = DnsProtocol.DOT,
            host = "94.140.14.14",
            port = 853,
            bootstrapIps = listOf("94.140.14.14", "94.140.15.15"),
            sni = "dns.adguard-dns.com",
        ),
        DnsServer(
            id = "ali-doh",
            name = "AliDNS",
            protocol = DnsProtocol.DOH,
            host = "dns.alidns.com",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("223.5.5.5", "223.6.6.6"),
            sni = "dns.alidns.com",
        ),
        DnsServer(
            id = "ali-dot",
            name = "AliDNS",
            protocol = DnsProtocol.DOT,
            host = "223.5.5.5",
            port = 853,
            bootstrapIps = listOf("223.5.5.5", "223.6.6.6"),
            sni = "dns.alidns.com",
        ),
        DnsServer(
            id = "dnspod-doh",
            name = "DNSPod",
            protocol = DnsProtocol.DOH,
            host = "doh.pub",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("1.12.12.12", "120.53.53.53"),
            sni = "doh.pub",
        ),
        DnsServer(
            id = "dnspod-dot",
            name = "DNSPod",
            protocol = DnsProtocol.DOT,
            host = "1.12.12.12",
            port = 853,
            bootstrapIps = listOf("1.12.12.12", "120.53.53.53"),
            sni = "dot.pub",
        ),
        DnsServer(
            id = "opendns-doh",
            name = "OpenDNS",
            protocol = DnsProtocol.DOH,
            host = "doh.opendns.com",
            port = 443,
            path = "/dns-query",
            bootstrapIps = listOf("208.67.222.222", "208.67.220.220"),
            sni = "doh.opendns.com",
        ),
        DnsServer(
            id = "opendns-dot",
            name = "OpenDNS",
            protocol = DnsProtocol.DOT,
            host = "208.67.222.222",
            port = 853,
            bootstrapIps = listOf("208.67.222.222", "208.67.220.220"),
            sni = "dns.opendns.com",
        ),
    )

    val defaultSelectedIds: Set<String> = setOf(
        "cf-doh",
        "cf-dot",
        "google-doh",
        "google-dot",
        "ali-doh",
        "ali-dot",
    )

    fun byId(id: String): DnsServer? = all.firstOrNull { it.id == id }
}
